export const runtime = "nodejs"

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-[#020617] text-white px-6 py-20">
      
      {/* Container */}
      <div className="max-w-4xl mx-auto">
        
        {/* Header */}
        <div className="mb-10 text-center">
          <h1 className="text-3xl md:text-4xl font-serif tracking-tight">
            Terms & Privacy
          </h1>
          <div className="w-16 h-px bg-amber-500 mx-auto mt-4"></div>
        </div>

        {/* Card */}
        <div className="bg-white/5 backdrop-blur-xl border border-white/10 rounded-2xl p-8 md:p-10 shadow-2xl">

          {/* Content */}
          <div className="whitespace-pre-line text-[15px] leading-relaxed text-white/80">
{`TERMS OF SERVICE           
Effective Date: 25/03/2026
Entity: SPEAR Protocol

1. Nature of Service
SPEAR Protocol is an AI-powered decision structuring platform designed to assist users in analyzing situations and generating structured outputs based solely on user-provided inputs.
The platform does not provide advice of any kind and should be used as a support tool only.

________________________________________

2. No Professional Advice
All outputs generated by SPEAR Protocol are for informational purposes only.
They do not constitute legal, financial, investment, or business advice.
Users remain fully responsible for all decisions and outcomes.

________________________________________

3. User Responsibilities
By using the platform, you agree that:
• You will provide accurate and lawful information 
• You have the right to share any data submitted 
• You will not rely solely on AI-generated outputs for critical decisions 
• You understand outputs may not reflect real-world outcomes 

________________________________________

4. AI Output Limitations
SPEAR Protocol uses automated systems to generate responses. Outputs may:
• Be incomplete or inaccurate 
• Lack context 
• Contain errors 
No guarantees are made regarding accuracy, reliability, or suitability.

________________________________________

5. Voice & Audio Processing
Voice input features may use browser-based speech recognition and third-party services.
Voice output may be generated via external providers.
By using these features, you consent to such processing.

________________________________________

6. Email & PDF Delivery
Outputs may be delivered via email and downloadable as PDF files.
This process may involve third-party services.
Users are responsible for ensuring that submitted content does not include sensitive or restricted information.

________________________________________

7. Subscription & Billing
• Subscription Fee: $499/month 
• Billing is recurring and automatic 
• Users may cancel anytime before the next billing cycle 
• No refunds for partial usage unless required by law 

________________________________________

8. Limitation of Liability
To the maximum extent permitted by law, SPEAR Protocol shall not be liable for:
• Any direct or indirect damages 
• Financial or business losses 
• Decisions made using the platform 

________________________________________

9. Termination
We reserve the right to suspend or terminate access if misuse or policy violations occur.

________________________________________

10. Governing Law
This agreement shall be governed by the laws of UK

________________________________________

🔐 PRIVACY POLICY

1. Information We Collect
We may collect:
• User input (text and voice transcripts) 
• AI-generated outputs 
• Email address 
• Usage and session data 

________________________________________

2. How We Use Data
Your data is used to:
• Generate decision outputs 
• Deliver PDFs and emails 
• Improve platform performance 

________________________________________

3. Voice Processing
Voice inputs may be processed using browser-based tools and third-party providers such as
ElevenLabs

________________________________________

4. Third-Party Services
We use third-party providers including:
• Brevo (email delivery) 
• Payment processors (e.g., Stripe) 
• Voice services
These services may process data under their own policies.

________________________________________

5. Data Storage
• Sessions may be stored for user access 
• We do not guarantee permanent storage 
• Users should retain copies of important outputs 

________________________________________

6. Data Security
We implement reasonable safeguards but cannot guarantee complete security.

________________________________________

7. User Rights
Users may request:
• Access to their data 
• Deletion of their data 
Requests can be made via the support email.

________________________________________

AI DISCLAIMER 
SPEAR Protocol generates AI-based decision frameworks based solely on user input.
These outputs are not advice and should not be relied upon as the sole basis for any decision.
You remain fully responsible for all actions taken.

________________________________________

VOICE FEATURE DISCLAIMER 
Voice input may be processed using third-party services.
By using this feature, you consent to such processing.

________________________________________

EMAIL & DOWNLOAD DISCLAIMER
Generated outputs may be stored and transmitted via third-party services for delivery.
Do not submit sensitive or confidential information unless you accept this risk.

________________________________________

SUBSCRIPTION POLICY
• Monthly subscription: $499 
• Auto-renewal enabled 
• Cancel anytime before next billing date 
• No refunds for partial billing cycles 
• Access continues until the end of the billing period `}
          </div>

        </div>
      </div>
    <footer className="relative border-t border-white/5 bg-[#020617] py-10 px-6">
        <div className="max-w-7xl mx-auto flex flex-col md:flex-row justify-between items-center gap-6 text-sm">
          <div className="flex items-center gap-3">
            <svg className="w-5 h-5 text-amber-500/50" viewBox="0 0 40 40" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path d="M20 4 L24 12 L20 10 L16 12 L20 4Z" fill="#F59E0B"/>
              <rect x="19" y="10" width="2" height="20" fill="#F59E0B"/>
              <rect x="17" y="30" width="6" height="2" fill="#F59E0B"/>
            </svg>
            <span className="text-white/30 hover:text-white/50 transition-colors">
              SPEAR Protocol — A Crowbar Ventures Instrument
            </span>
          </div>
          
          <div className="flex gap-8">
            <div className="text-white/30 hover:text-amber-400 transition-colors cursor-pointer">
              spearprotocol.com
            </div>
            <div className="w-px h-4 bg-white/20"></div>
            <div className="text-white/30 hover:text-white/50 transition-colors">
              Private and Confidential
            </div>
          </div>
        </div>
      </footer>
    </main>
  )
}